### ISSUE TITLE
Box closes as soon as it is opened.

### ISSUE THREAD

**Issue by Mattthecow** [bluepnume/brainblocks#1]
As shown in the following gif:
[![https://gyazo.com/f536fa50923b9b15f9c0f9ee6ee9521f](https://i.gyazo.com/f536fa50923b9b15f9c0f9ee6ee9521f.gif)](https://gyazo.com/f536fa50923b9b15f9c0f9ee6ee9521f)

As soon as the box is clicked it closes itself again.

**Comment by bluepnume** [comment]
Thanks for the report. Looks like my rai node ran out of wallet addresses. I've cleaned it up -- can you try again? Thanks!

**Comment by guilhermelawless** [comment]
It was failing for me yesterday, fixed today. Nice!

**Comment by bluepnume** [comment]
Woot! Thanks for checking
